// Add this inside your existing translations object
translations.pt = Object.assign(translations.pt || {}, {
  "about_early_days": "O MSX do Tiago\nSempre gostei de computadores e tecnologia. Desde muito novo, fiquei fascinado pelas maravilhas da tecnologia e em como as coisas funcionavam. A minha jornada come\u00e7ou com videojogos, com consolas como a Master System e a Mega Drive. No entanto, n\u00e3o eram apenas os jogos que me cativavam; era a tecnologia por tr\u00e1s deles que me despertava ainda mais curiosidade.",
  "about_first_pc": "O meu primeiro computador foi um MSX, mais precisamente um Gradiente Expert DD Plus, onde comecei a aprender conceitos de programa\u00e7\u00e3o com LOGO e BASIC. Esse contacto inicial com programa\u00e7\u00e3o despertou uma paix\u00e3o pela tecnologia que s\u00f3 se intensificou ao longo dos anos.",
  "about_386_486": "\u00c0 medida que me aprofundava no mundo dos computadores, comecei a configurar placas de som, gerir IRQs e definir DMAs apenas para fazer os jogos funcionarem no meu 386 ou 486. A satisfa\u00e7\u00e3o de ultrapassar esses desafios t\u00e9cnicos alimentava ainda mais a minha vontade de aprender.",
  "about_building_pcs": "Levei o meu entusiasmo mais al\u00e9m ao montar os meus pr\u00f3prios computadores, come\u00e7ando com 486s, passando para os Pentiums e at\u00e9 os processadores K6-2. Esta experi\u00eancia pr\u00e1tica foi inestim\u00e1vel e consolidou o meu gosto por hardware e configura\u00e7\u00e3o de sistemas. Na adolesc\u00eancia, trabalhei numa loja de inform\u00e1tica a fazer manuten\u00e7\u00e3o, onde ganhei experi\u00eancia pr\u00e1tica e aperfei\u00e7oei as minhas compet\u00eancias.",
  "about_machines_dreams": "Para al\u00e9m dos computadores, sempre tive uma grande fascina\u00e7\u00e3o por m\u00e1quinas e motores. Barcos, comboios, avi\u00f5es e cami\u00f5es alimentavam a minha imagina\u00e7\u00e3o. Cheguei at\u00e9 a considerar ser camionista ou seguir uma carreira em arquitectura ou engenharia civil. No entanto, o apelo dos computadores falou mais alto e ficou claro que o meu futuro estaria ligado \u00e0 tecnologia.",
  "about_career_linux": "No final dos anos 90, trabalhava no help desk e pouco depois comecei a trabalhar com administra\u00e7\u00e3o de redes com Novell e Windows NT. A minha carreira mudou significativamente quando descobri o Linux na feira de inform\u00e1tica FENASOFT...",
  "about_title": "Sobre Mim"
});
translations.en = Object.assign(translations.en || {}, {
  "about_early_days": "Tiago's MSX\nI always liked computers and technology. From my early days, I was fascinated by the wonders of technology and how things worked. My journey started with video games, having consoles like the Master System and Mega Drive. However, it was not just the games that captured my interest; it was the technology behind them that intrigued me even more.",
  "about_first_pc": "My first computer was an MSX, specifically a Gradiente Expert DD Plus, where I began learning programming concepts with LOGO and BASIC. This early exposure to programming sparked a passion for technology that would only grow stronger over the years.",
  "about_386_486": "As I delved deeper into the world of computers, I found myself configuring sound cards, managing IRQs, and setting up DMA just to make games work on my 386 or 486. The satisfaction of solving these technical challenges fueled my desire to learn more.",
  "about_building_pcs": "I took my enthusiasm a step further by building my own computers, starting with 486s, moving on to Pentiums, and even the K6-2 processors. This hands-on experience was invaluable and cemented my love for hardware and system configuration. During my teenage years, I worked at a computer shop doing maintenance, gaining practical experience and honing my skills.",
  "about_machines_dreams": "Besides computers, I was also fascinated by machines and engines. Boats, trains, airplanes, and trucks captured my imagination. At one point, I even considered becoming a truck driver or pursuing a career in architecture or civil engineering. However, the allure of computers was too strong, and it became clear that my future lay in technology.",
  "about_career_linux": "In the late 1990s, I was working in help desk and shortly after that with network administration with Novell and Windows NT. My career took a significant turn when I discovered Linux at the FENASOFT computer fair...",
  "about_title": "About Me"
});